---

# PACKET FLOW (*** no VLAN, === VLAN)
#
#   patch-br1 ** br0 ** pf0 ******************
#       *
#       *
#   patch-br0 ** br1 == pf1 ==================

- name: add patch port
  command: >
    ovs-vsctl add-port br0 patch-br1 --
      set interface patch-br1 type=patch options:peer=patch-br0 --
      add-port br1 patch-br0 --
      set interface patch-br0 type=patch options:peer=patch-br1

- name: set port names
  set_fact:
    left_port: patch-br0
    right_port: pf1
