#Edit this according to your setup.
#Keep the dut and tgen aliases as those are used in the playbooks

all:
  vars:
    trex_dir: /tmp/trex-core

  hosts:
    dut:
      # edit according to your platform
      ansible_host: rhos-nfv-11.lab.eng.rdu2.redhat.com
      reset_cmds:
        - pkill -x dpdk-testpmd || true
        - for br in `ovs-vsctl list-br`; do for p in `ovs-vsctl list-ports $br`; do ovs-vsctl del-port $br $p; done; ovs-vsctl del-br $br; done
        - systemctl stop openvswitch.service
        - rm -f /etc/openvswitch/conf.db
        - echo 0 > /sys/class/net/enp196s0f0/device/sriov_numvfs
        - echo 0 > /sys/class/net/enp196s0f1/device/sriov_numvfs
        - devlink dev eswitch set pci/0000:c4:00.0 mode legacy
        - devlink dev eswitch set pci/0000:c4:00.1 mode legacy
        - sleep 5

      # hardware offload datapath
      hwol:
        # expected performance results
        cps_ct_short: 10000
        cps_ct_long: 1500
        # edit according to your platform
        setup_cmds:
          - devlink dev param set pci/0000:c4:00.0 name flow_steering_mode value smfs cmode runtime
          - devlink dev param set pci/0000:c4:00.1 name flow_steering_mode value smfs cmode runtime
          - devlink dev eswitch set pci/0000:c4:00.0 mode switchdev
          - devlink dev eswitch set pci/0000:c4:00.1 mode switchdev
          - ethtool -G enp196s0f0 rx 4096 tx 4096
          - ethtool -G enp196s0f1 rx 4096 tx 4096
          - ethtool -L enp196s0f0 combined 1
          - ethtool -L enp196s0f1 combined 1
          - echo 2 > /sys/class/net/enp196s0f0/device/sriov_numvfs
          - echo 2 > /sys/class/net/enp196s0f1/device/sriov_numvfs
          - systemctl start openvswitch.service
          - ovs-vsctl set Open_vSwitch . other_config:hw-offload=true
          - ovs-vsctl add-br br0
          - ovs-vsctl add-br br1
          - ovs-vsctl add-port br0 enp196s0f0
          - ovs-vsctl add-port br0 eth0
          - ovs-vsctl add-port br1 enp196s0f1
          - ovs-vsctl add-port br1 eth2
          - nohup dpdk-testpmd -a 0000:c4:00.2 -a 0000:c4:08.2 -l 4,5,6 -- --nb-cores=2 --rxd=4096 --txd=4096 --stats-period 5 </dev/null >/tmp/testpmd.log 2>&1 &
          - sleep 5

      # userspace dpdk datapath
      dpdk:
        # expected performance results
        cps_ct_short: 60000
        cps_ct_long: 1500
        # edit according to your platform
        setup_cmds:
          - systemctl start openvswitch.service
          - ovs-vsctl set open_vswitch . other_config:dpdk-init=true
          - ovs-vsctl set open_vswitch . other_config:pmd-cpu-mask="0x100000000000000010"
          - systemctl restart openvswitch.service
          - sleep 1
          - ovs-vsctl add-br br0 -- set bridge br0 datapath_type=netdev
          - ovs-vsctl add-br br1 -- set bridge br1 datapath_type=netdev
          - ovs-vsctl add-port br0 pf0 -- set Interface pf0 type=dpdk options:dpdk-devargs=0000:c4:00.0 options:n_rxq_desc=4096 options:n_txq_desc=4096 options:n_rxq=2
          - ovs-vsctl add-port br1 pf1 -- set Interface pf1 type=dpdk options:dpdk-devargs=0000:c4:00.1 options:n_rxq_desc=4096 options:n_txq_desc=4096 options:n_rxq=2
          - ovs-vsctl add-port br0 patch0 -- set interface patch0 type=patch options:peer=patch1 -- add-port br1 patch1 -- set interface patch1 type=patch options:peer=patch0

    tgen:
      # edit according to your platform
      ansible_host: rhos-nfv-12.lab.eng.rdu2.redhat.com
      trex_config:
        - version: 2
          interfaces:
            - 'c4:00.0'
            - 'c4:00.1'
          rx_desc: 4096
          tx_desc: 4096
          port_info:
            - dest_mac: 04:3f:72:f2:8f:33
              src_mac:  04:3f:72:f2:8f:32
            - dest_mac: 04:3f:72:f2:8f:32
              src_mac:  04:3f:72:f2:8f:33
          c: 46
          memory:
            mbuf_64: 30720
            mbuf_128: 500000
            mbuf_256: 30717
            mbuf_512: 30720
            mbuf_1024: 30720
            mbuf_2048: 4096
          platform:
            master_thread_id: 0
            latency_thread_id: 64
            dual_if:
              - socket: 0
                threads: [
                  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                  65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
                  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                  80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
                ]
