# Edit this according to your setup.
# Keep the dut and tgen aliases as those are used in the playbooks
#
# Expected topology;
#
# +-----+  vlan 210-215  +------+
# |     |----------------|      |
# | dut |  vlan 210-215  | tgen |
# |     |----------------|      |
# +-----+                +------+

all:
  vars:
    trex_dir: /tmp/trex-core
    datapath: dpdk
    vlan: 212

  hosts:
    dut:
      # edit according to your platform
      ansible_host: rhos-nfv-11.lab.eng.rdu2.redhat.com
      ports:
        - '0000:c4:00.0'
        - '0000:c4:00.1'
      port_macs:
        - 04:3f:72:f2:8f:f2
        - 04:3f:72:f2:8f:f3
      dpdk_core_mask: '0x100000000000000010'
      dpdk_lcore_mask: '0x1'
      dpdk_socket_mem: '2048,2048'
      n_rxq: 1
      queue_descriptors: 4096
      max_conntrack: 50000000
      # only used for hardware offload
      testpmd_core_ids: '4,5,6'
      testpmd_nb_cores: 2
      num_vfs: 2

      # expected results for every datapath
      hwol:
        cps_ct_short: 10000
        cps_ct_long: 4000
        conntrack_flush_cmd: conntrack -F
        vlan_pps: 14600000
        vxlan_pps: 300000
      dpdk:
        cps_ct_short: 55000
        cps_ct_long: 500
        conntrack_flush_cmd: ovs-appctl dpctl/flush-conntrack
        vlan_pps: 8400000
        vxlan_pps: 6000000

    tgen:
      # edit according to your platform
      ansible_host: rhos-nfv-12.lab.eng.rdu2.redhat.com
      trex_config:
        - version: 2
          interfaces:
            - 'c4:00.0'
            - 'c4:00.1'
          rx_desc: 4096
          tx_desc: 4096
          port_info:
            - dest_mac: 04:3f:72:f2:8f:33
              src_mac:  04:3f:72:f2:8f:32
            - dest_mac: 04:3f:72:f2:8f:32
              src_mac:  04:3f:72:f2:8f:33
          c: 46
          memory:
            mbuf_64: 30720
            mbuf_128: 500000
            mbuf_256: 30717
            mbuf_512: 30720
            mbuf_1024: 30720
            mbuf_2048: 4096
          platform:
            master_thread_id: 0
            latency_thread_id: 64
            dual_if:
              - socket: 0
                threads: [
                  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                  65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
                  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                  80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
                ]

    dut_bond:
      # edit according to your platform
      ansible_host: wsfd-advnetlab147.lab3.eng.bos.redhat.com
      ports:
        - '0000:ca:00.0'
        - '0000:ca:00.1'
      dpdk_lcore_mask: '0xa8000002a8000002'
      dpdk_core_mask:       '0x2a8000002a8'
      dpdk_socket_mem: '0,2048'
      vhost_macs:
        - vhost: fa:16:3e:ea:c6:9a
          tgen: b4:96:91:b7:9e:24
          vlan: 524
        - vhost: fa:16:3e:09:81:e4
          tgen: b4:96:91:b7:9e:25
          vlan: 520
      rxq: 2
      rhel_image:  http://rhos-qe-mirror-qeos.usersys.redhat.com/brewroot/packages/rhel-guest-image/8.4/1261/images/rhel-guest-image-8.4-1261.x86_64.qcow2
      vcpu_pinning:
        0: 15
        1: 47
        2: 17
        3: 49
        4: 19
        5: 51
      dpdk:
        lag_pps_60: 1
        lag_pps_512: 1
        lag_pps_1280: 1

    tgen_bond:
      # edit according to your platform
      ansible_host: wsfd-advnetlab148.lab3.eng.bos.redhat.com
      trex_config:
        - version: 2.98
          interfaces:
            - 'ca:00.0'
            - 'ca:00.1'
          rx_desc: 4096
          tx_desc: 4096
          port_info:
            - dest_mac: 00:00:00:00:00:01
              src_mac:  b4:96:91:b7:9e:24
            - dest_mac: 00:00:00:00:00:02
              src_mac:  b4:96:91:b7:9e:25
          memory:
            mbuf_64: 30720
            mbuf_128: 500000
            mbuf_256: 30717
            mbuf_512: 30720
            mbuf_1024: 30720
            mbuf_2048: 4096
          c: 30
          platform:
            master_thread_id: 1
            latency_thread_id: 33
            dual_if:
              - socket: 1
                threads: [
                  3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29,
                  31, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63,
                ]
