---

- hosts: dut
  vars:
    datapath: dpdk
  roles:
    - ovs-base
    - ovs-base-bridge
    - ovs-conntrack

- hosts: tgen
  vars:
    datapath: dpdk
    dut: '{{hostvars.dut.ansible_host}}'
    reset_command: '{{hostvars.dut[datapath].conntrack_flush_cmd}}'
  roles:
    - role: trex
      trex_opts: --astf

    - role: trex-cps-ndr
      udp_percent: 1
      min_cps: 1k
      max_cps: 200k
      message_size: 20
      num_messages: 1
      server_wait: 0
      sample_time: 10
      expected_cps: '{{hostvars.dut[datapath].cps_ct_short}}'

    - role: trex-cps-ndr
      udp_percent: 1
      min_cps: 100
      max_cps: 15k
      message_size: 20
      num_messages: 500
      server_wait: 50
      sample_time: 60
      expected_cps: '{{hostvars.dut[datapath].cps_ct_long}}'
