---

- name: start vswitchd
  service:
    name: openvswitch.service
    state: started

- name: initialize dpdk datapath
  command: ovs-vsctl set open_vswitch . other_config:{{item}}
  loop:
    - 'dpdk-init=true'
    - 'pmd-cpu-mask={{dpdk_core_mask}}'

- name: restart vswitchd
  service:
    name: openvswitch.service
    state: restarted

