---

- name: start vswitchd
  service:
    name: openvswitch.service
    state: started

- name: initialize dpdk datapath
  command: ovs-vsctl set open_vswitch . other_config:{{item}}
  loop:
    - 'dpdk-init=true'
    - 'pmd-cpu-mask={{dpdk_core_mask}}'

- name: restart vswitchd
  service:
    name: openvswitch.service
    state: restarted

- name: create base bridges and ports
  shell:
    cmd: |
      set -xe
      ovs-vsctl add-br br{{i}} -- set bridge br{{i}} datapath_type=netdev
      ovs-vsctl add-port br{{i}} pf{{i}} -- \
        set interface pf{{i}} type=dpdk options:dpdk-devargs={{item}} \
        options:n_rxq_desc={{queue_descriptors}} \
        options:n_txq_desc={{queue_descriptors}} \
        options:n_rxq={{n_rxq}}
  loop: "{{ ports }}"
  loop_control:
    index_var: i
