---

- name: configure bridges
  include_tasks: '{{datapath}}.yml'
  tags: setup

- name: reset flows
  command: ovs-ofctl del-flows br0

- name: configure flows
  command:
    cmd: ovs-ofctl --bundle add-flow br0 -
    stdin: |
      add table=0,priority=10,ip,ct_state=-trk     action=ct(table=0)
      add table=0,priority=10,ip,ct_state=+trk+new action=ct(commit),NORMAL
      add table=0,priority=10,ip,ct_state=+trk+est action=NORMAL
      add table=0,priority=0                       action=drop
  tags: setup
